export const GET_MENSPRODUCT_REQUEST = "GET_MENSPRODUCT_REQUEST";
export const GET_MENSPRODUCT_SUCCESS = "GET_MENSPRODUCT_SUCCESS";
export const GET_MENSPRODUCT_FAILURE = "GET_MENSPRODUCT_FAILURE";

export const GET_WOMENSPRODUCT_REQUEST = "GET_WOMENSPRODUCT_REQUEST";
export const GET_WOMENSPRODUCT_SUCCESS = "GET_WOMENSPRODUCT_SUCCESS";
export const GET_WOMENSPRODUCT_FAILURE = "GET_WOMENSPRODUCT_FAILURE";

export const GET_SHOES_REQUEST = "GET_SHOES_REQUEST";
export const GET_SHOES_SUCCESS = "GET_SHOES_SUCCESS";
export const GET_SHOES_FAILURE = "GET_SHOES_FAILURE";